### ISSUE TITLE
kube-explorer does not support being installed behind a shared ingress gateway

### ISSUE THREAD

**Issue by wkbrd** [niusmallnan/kube-explorer#42]
Please enhance the software to support a prepended URI.  This way we can present kube-explorer as an application behind a shared ingress gateway.  For example, allow all URIs to be prepended with a configurable token (such as /kube-explorer) so that other applications can be available at other endpoints on the same public host.

A possible partial solution is if the ingress rule rewrites the URL.  Though this depends on the UI being able to work with this configuration.

Right now, it appears that the following top-level endpoints are necessary (and possibly others):
- /dashboard
- /v1
- /k8s
- /api/v1
- /apis

**Comment by orangedeng** [comment]
I did a research about this topic and the followings are the key points.

- The steve backend has `X-API-URL-PREFIX` and the XFF headers to provide the reverse proxy function.
- The problem is the UI resources. It has the fixed base href in https://github.com/cnrancher/kube-explorer-ui/blob/v2.8.0-kube-explorer-ui-rc3/shell/public/index.html#L8

It can be implemented by traefik/nginx to modify the response html content. Change the base href from `/dashboard/` to `/<prefix-you-need>/dashboard/` and it should be ok. That's the way how autok3s achieve this. But the response html is encoded by `gzip` so you might need to handle the encode/decode first.

I will suggest using sub-domain instead of sub-path if possible.

**Comment by orangedeng** [comment]
After refactor the kube-explorer, this is implementable. Put into v0.5.0 milestone.
